services:
  nginx:
    image: nginx:latest
    container_name: minio-proxy
    ports:
      - "9000:9000"
    depends_on:
      - minio
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      app-network:
        aliases:
          - miniogw

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_SERVER_URL: "http://miniogw:9000"
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    ports:
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "8003:3000"
    networks:
      - app-network

  frontend-test:
    build:
      context: .
      dockerfile: ./frontend_test/Dockerfile
    container_name: frontend-demo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8002:80"
    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./frontend_test/index.html
    #       target: /usr/share/nginx/html/index.html
    volumes:
      - ./frontend_test/index.html:/usr/share/nginx/html/index.html
      - ./frontend_test/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  api-gateway:
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8000:5000"
    volumes:
      - ./services/api-gateway/src:/app/services/api-gateway/src
      # - /app/.venv
    depends_on:
      - rabbitmq
      - redis
      - minio
    environment:
      RABBITMQ_SERVER_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_SERVER_URL: redis://redis:6379
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    restart: unless-stopped
    networks:
      - app-network

  ingestion:
    build:
      context: .
      dockerfile: ./services/ingestion/Dockerfile
    container_name: ingestion
    ports:
      - "8001:5001"
    volumes:
      - ./services/ingestion/src:/app/services/ingestion/src
      # - /app/.venv
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      api-gateway:
        condition: service_started
    environment:
      RABBITMQ_SERVER_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_SERVER_URL: redis://redis:6379
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    restart: unless-stopped
    networks:
      - app-network

  # vision-engine:
  #   build:
  #     context: .
  #     dockerfile: ./services/vision-engine/Dockerfile
  #   container_name: vision-engine
  #   ports:
  #     - "8004:5004"
  #   volumes:
  #     - ./services/vision-engine/src:/app/services/vision-engine/src
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     minio:
  #       condition: service_healthy
  #     api-gateway:
  #       condition: service_started
  #   environment:
  #     RABBITMQ_SERVER_URL: amqp://guest:guest@rabbitmq:5672/
  #     REDIS_SERVER_URL: redis://redis:6379
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin123
  #   restart: unless-stopped
  #   networks:
  #     - app-network

volumes:
  rabbitmq_data:
    driver: local
  minio_data:
    driver: local

networks:
  app-network:
    driver: bridge
